CREATE TABLE IF NOT EXISTS nb69_users (
 username VARCHAR(32) PRIMARY KEY,
 display_name VARCHAR(64) NOT NULL,
 admin BOOLEAN NOT NULL DEFAULT FALSE,
 password_hash VARCHAR(100),
 activation_hash VARCHAR(100),
 activation_expires TIMESTAMP WITH TIME ZONE
);
CREATE TABLE IF NOT EXISTS nb69_assignments (
 week_start DATE NOT NULL,
 task_id INTEGER NOT NULL,
 task_name VARCHAR(100) NOT NULL,
 username VARCHAR(32) NOT NULL REFERENCES nb69_users(username),
 completed_at TIMESTAMP WITH TIME ZONE,
 completed_by VARCHAR(32) REFERENCES nb69_users(username),
 PRIMARY KEY (week_start, task_id)
);
CREATE TABLE IF NOT EXISTS nb69_audit (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 actor VARCHAR(32) NOT NULL,
 action VARCHAR(64) NOT NULL,
 detail VARCHAR(255) NOT NULL,
 recorded_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE IF NOT EXISTS nb69_email_contacts (
 username VARCHAR(32) PRIMARY KEY REFERENCES nb69_users(username),
 email VARCHAR(254) NOT NULL
);
CREATE TABLE IF NOT EXISTS nb69_email_reminders (
 week_start DATE NOT NULL,
 task_id INTEGER NOT NULL,
 kind VARCHAR(20) NOT NULL,
 username VARCHAR(32) NOT NULL,
 status VARCHAR(30) NOT NULL,
 provider_id VARCHAR(100),
 attempted_at TIMESTAMP WITH TIME ZONE NOT NULL,
 PRIMARY KEY (week_start, task_id, kind)
);

-- Version the default rota without rewriting past weeks or admin overrides.
ALTER TABLE nb69_assignments ADD COLUMN IF NOT EXISTS rotation_version INTEGER NOT NULL DEFAULT 0;

ALTER TABLE nb69_email_contacts ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE nb69_email_contacts ADD COLUMN IF NOT EXISTS token_hash VARCHAR(64);
ALTER TABLE nb69_email_contacts ADD COLUMN IF NOT EXISTS token_expires TIMESTAMP WITH TIME ZONE;
CREATE TABLE IF NOT EXISTS nb69_email_verification_limits (
 username VARCHAR(32) PRIMARY KEY REFERENCES nb69_users(username),
 last_sent TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS nb69_avatars (
 username VARCHAR(32) PRIMARY KEY REFERENCES nb69_users(username),
 image_base64 VARCHAR(300000) NOT NULL,
 version VARCHAR(36) NOT NULL
);

ALTER TABLE nb69_assignments ADD COLUMN IF NOT EXISTS completion_comment VARCHAR(500);

CREATE TABLE IF NOT EXISTS nb69_swaps (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 requester VARCHAR(32) NOT NULL REFERENCES nb69_users(username),
 recipient VARCHAR(32) NOT NULL REFERENCES nb69_users(username),
 away_week DATE NOT NULL,
 away_task INTEGER NOT NULL,
 return_week DATE NOT NULL,
 return_task INTEGER NOT NULL,
 status VARCHAR(20) NOT NULL,
 FOREIGN KEY (away_week,away_task) REFERENCES nb69_assignments(week_start,task_id),
 FOREIGN KEY (return_week,return_task) REFERENCES nb69_assignments(week_start,task_id)
);
CREATE TABLE IF NOT EXISTS nb69_shopping (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 added_by VARCHAR(32) NOT NULL REFERENCES nb69_users(username),
 bought_by VARCHAR(32) REFERENCES nb69_users(username)
);
