CREATE TABLE IF NOT EXISTS nb69_users (
 username VARCHAR(32) PRIMARY KEY,
 display_name VARCHAR(64) NOT NULL,
 admin BOOLEAN NOT NULL DEFAULT FALSE,
 password_hash VARCHAR(100),
 activation_hash VARCHAR(100),
 activation_expires TIMESTAMP WITH TIME ZONE
);
CREATE TABLE IF NOT EXISTS nb69_assignments (
 week_start DATE NOT NULL,
 task_id INTEGER NOT NULL,
 task_name VARCHAR(100) NOT NULL,
 username VARCHAR(32) NOT NULL REFERENCES nb69_users(username),
 completed_at TIMESTAMP WITH TIME ZONE,
 completed_by VARCHAR(32) REFERENCES nb69_users(username),
 PRIMARY KEY (week_start, task_id)
);
CREATE TABLE IF NOT EXISTS nb69_audit (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 actor VARCHAR(32) NOT NULL,
 action VARCHAR(64) NOT NULL,
 detail VARCHAR(255) NOT NULL,
 recorded_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE IF NOT EXISTS nb69_email_contacts (
 username VARCHAR(32) PRIMARY KEY REFERENCES nb69_users(username),
 email VARCHAR(254) NOT NULL
);
CREATE TABLE IF NOT EXISTS nb69_email_reminders (
 week_start DATE NOT NULL,
 task_id INTEGER NOT NULL,
 kind VARCHAR(20) NOT NULL,
 username VARCHAR(32) NOT NULL,
 status VARCHAR(30) NOT NULL,
 provider_id VARCHAR(100),
 attempted_at TIMESTAMP WITH TIME ZONE NOT NULL,
 PRIMARY KEY (week_start, task_id, kind)
);
